// Top-level build file where you can add configuration options common to all sub-projects/modules.
apply plugin: 'base'
buildscript {
    ext {
        Properties properties = new Properties()
        properties.load(project.rootProject.file('local.properties').newDataInputStream())

        lancet_group = 'me.ele'
        lancet_version = '1.0.6'
        asm_version = '5.1'
        android_tools_version = '4.2.0'
        guava_version = '24.0'
    }

    repositories {
        mavenLocal()
        google()
        mavenCentral()
        gradlePluginPortal()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:$android_tools_version"
        classpath project(':lancet-plugin') // 本地插件工程
        // 这种方式是本地多模块工程开发插件的标准做法，不需要先发布到 mavenLocal。
        // 如果想在其他项目中用 Lancet，可以先 ./gradlew lancet-plugin:publishToMavenLocal，然后在 buildscript 里用 classpath 'me.ele:lancet-plugin:1.0.6'。
    }
}
allprojects {
    repositories {
        mavenLocal()
        mavenCentral()
        google()
    }
}