apply plugin: 'java'

dependencies {
    testImplementation "junit:junit:4.12"
    testImplementation 'com.squareup.okio:okio:1.11.0'
    testImplementation 'org.assertj:assertj-core:3.6.2'

    compileClasspath "com.google.guava:guava:$guava_version"
    implementation "org.ow2.asm:asm-all:$asm_version"
    implementation gradleApi()
    compileClasspath "com.android.tools.build:gradle:$android_tools_version"
    implementation project(':lancet-api')
}

sourceCompatibility = "1.8"
targetCompatibility = "1.8"


