apply plugin: 'com.android.application'
apply plugin: 'me.ele.lancet'

android {
    compileSdkVersion 30
    defaultConfig {
        applicationId "com.sample.playground"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation project(":lancet-api")
    testImplementation 'junit:junit:4.13.2'
}

task executeTestSample(type:JavaExec) {
    main = "com.sample.playground.Main"
    classpath = files('build/classes/java/main')
}

task executeTestSampleProduct(type:JavaExec) {
    main = "com.sample.playground.Main"
    classpath = files('build/product/java/main')
}

sourceCompatibility = "1.8"
targetCompatibility = "1.8"