apply plugin: 'java-gradle-plugin'
apply plugin: 'maven-publish'

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation gradleApi()
    compileOnly "com.android.tools.build:gradle:$android_tools_version"
    implementation "com.google.code.gson:gson:2.8.0"
    implementation project(':lancet-weaver')
    implementation project(':lancet-api')
    testImplementation gradleTestKit()
    testImplementation 'junit:junit:4.12'
}

sourceCompatibility = "1.8"
targetCompatibility = "1.8"

task createClasspathManifest {
    def outputDir = file("$buildDir/$name")

    inputs.files sourceSets.main.runtimeClasspath
    outputs.dir outputDir

    doLast {
        outputDir.mkdirs()
        file("$outputDir/plugin-classpath.txt").text = sourceSets.main.runtimeClasspath.join("\n")
    }
}

dependencies {
    testRuntimeOnly files(createClasspathManifest)
}

gradlePlugin {
    plugins {
        lancet {
            id = 'me.ele.lancet'
            implementationClass = 'me.ele.lancet.plugin.LancetPlugin'
        }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}